[package]
name = "FileNewer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe =  "0.27.2"
# For image support:
egui_extras = "0.27.2"

env_logger = "0.11.3"
lorem-ipsum-generator = "0.1.0"
chrono = "0.4.38"